// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqK9D41E-R9GY1_xOtYM0eo-6v0kdLZyg',
    appId: '1:739235439031:web:15028973146ce9e9c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    authDomain: 'agrimarket-60402.firebaseapp.com',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    measurementId: 'G-SR4ZD7QLPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKk5iB7TtCPhYdvIohhO9dxr-MTrteA8',
    appId: '1:739235439031:android:e210014a64123ae6c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjzYdwfdsxphdIuD6eruqg9Tvnvk1G2g',
    appId: '1:739235439031:ios:dfd733f53d5bee54c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    androidClientId: '739235439031-rc4bk9ohpgk4r4c7u6eeosamg5p3banl.apps.googleusercontent.com',
    iosClientId: '739235439031-79m693sb2vorve0lqg8p3quq3g7sv1uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGjzYdwfdsxphdIuD6eruqg9Tvnvk1G2g',
    appId: '1:739235439031:ios:dfd733f53d5bee54c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    androidClientId: '739235439031-rc4bk9ohpgk4r4c7u6eeosamg5p3banl.apps.googleusercontent.com',
    iosClientId: '739235439031-79m693sb2vorve0lqg8p3quq3g7sv1uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqK9D41E-R9GY1_xOtYM0eo-6v0kdLZyg',
    appId: '1:739235439031:web:477b8ce4da86dfa6c5c832',
    messagingSenderId: '739235439031',
    projectId: 'agrimarket-60402',
    authDomain: 'agrimarket-60402.firebaseapp.com',
    storageBucket: 'agrimarket-60402.firebasestorage.app',
    measurementId: 'G-DETX3X5K3Z',
  );
}
